image: node:10

before_script:
  - yarn

test:node:10:
  stage: test
  image: node:10
  script:
    - yarn test

publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - yarn build
    - echo '//registry.npmjs.org/:_authToken=${CAZOO_NPM_TOKEN}'>.npmrc
    - yarn publish
